name: Update Weekly Summaries

on:
  schedule:
    - cron: '*/5 * * * *'  # Run every Sunday at midnight UTC

jobs:
  update_summaries:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Create and Activate Virtual Environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Python Script
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          python summaries.py
